service: giftcard
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt GiftCardTable.Arn

  environment:
    CARDS: !Ref GiftCardTable

functions:
  CreateCard:
    handler: src/lambdas/CreateCard.handler
    events:
      - httpApi:
          path: card
          method: post
  GetCard:
    handler: src/lambdas/GetCard.handler
    events:
      - httpApi:
          path: card
          method: get
  UseCard:
    handler: src/lambdas/UseCard.handler
    events:
      - httpApi:
          path: card
          method: put

resources:
  Resources:
    GiftCardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-${self:provider.stage}-giftcards-table